b-402: Clarifying what Job HP and MP bonuses are
atmafox/FFRPG4e pull request #333
Opened 2020-03-19 01:58 UTC by BrunoCarvalhoPaula

Clarifying what Job HP and MP bonuses are.

2020-03-22 15:14 UTC, atmafox requested changes
Please see comments for requested change!

2020-03-22 15:14 UTC, atmafox commented on core/revised/gmguide.tex
> +\begin{center}
Should include the interntional-blank here like it was in core/revised.tex

2020-03-22 15:41 UTC, atmafox commented on core/revised/gmguide.tex
> +\begin{center}
I made these changes

2020-03-23 01:39 UTC, WeaverThree submitted a review, later dismissed
Seems good

2020-03-23 17:31 UTC, WeaverThree approved these changes

2020-03-23 17:58 UTC, atmafox approved these changes
LGTM now!

2020-03-23 17:59 UTC, merged